version: '3'

services:
  my_app:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: sh -c "pip install pipenv && pipenv install && pipenv run python3 app.py"
